### ISSUE TITLE
Please delete this repo

### ISSUE THREAD

**Issue by dreamflasher** [standardnotes/extensions#1]
Google search finds this repo as a first result, and then one needs to copy the correct url.

**Comment by atmoio** [comment]
For what query? I'd say then it's doing its job. We could improve the documentation here at some point to make it more useful. Would be difficult to find sn-extensions org without this.

**Comment by dreamflasher** [comment]
`github standard notes extensions` and `github standardnotes extensions` – for some reason `https://github.com/sn-extensions` does not appear in the top 10 results. Maybe you could rename the title of https://github.com/sn-extensions from `SN Extensions` to `Standard Notes Exentions`? That might help to find it.

**Comment by atmoio** [comment]
Done 👍

**Comment by dreamflasher** [comment]
Thank you! Let's see if this already helps.
